# Generated by Django 3.0.3 on 2020-02-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nacionalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.IntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('apelido', models.CharField(max_length=200)),
            ],
        ),
    ]
