# Generated by Django 3.0.3 on 2020-02-13 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pre_cadastro', '0002_nacionalidade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nacionalidade',
        ),
    ]
