# Generated by Django 3.0.3 on 2020-02-13 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pre_cadastro', '0004_auto_20200213_2018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genero',
            new_name='Sexo',
        ),
        migrations.RenameField(
            model_name='candidato',
            old_name='genero',
            new_name='sexo',
        ),
    ]
