# Generated by Django 3.0.3 on 2020-02-14 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pre_cadastro', '0005_auto_20200213_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.IntegerField()),
                ('titulo', models.CharField(max_length=100)),
                ('apelido', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='candidato',
            name='estado_civil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pre_cadastro.EstadoCivil'),
        ),
    ]
