# Generated by Django 3.0.3 on 2020-02-14 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pre_cadastro', '0006_auto_20200214_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.IntegerField()),
                ('titulo', models.CharField(max_length=50)),
                ('apelido', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='candidato',
            name='responsavel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pre_cadastro.Responsavel'),
        ),
    ]
