# Generated by Django 3.0.3 on 2020-02-14 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pre_cadastro', '0007_auto_20200214_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='estado_civil',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pre_cadastro.EstadoCivil'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nacionalidade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pre_cadastro.Nacionalidade'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='responsavel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pre_cadastro.Responsavel'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='sexo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pre_cadastro.Sexo'),
        ),
    ]
