# Generated by Django 3.0.3 on 2020-02-14 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pre_cadastro', '0010_auto_20200214_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportePublico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.IntegerField()),
                ('titulo', models.CharField(max_length=10)),
                ('apelido', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='candidato',
            name='transporte_publico',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pre_cadastro.TransportePublico'),
        ),
    ]
