# Generated by Django 3.0.3 on 2020-02-15 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pre_cadastro', '0013_auto_20200214_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='estado_naturalidade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='EstadoNaturalidade', to='pre_cadastro.Estado'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='estado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Estado', to='pre_cadastro.Estado'),
        ),
    ]
