# Generated by Django 3.0.3 on 2020-02-27 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pre_cadastro', '0015_raca'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='raca',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pre_cadastro.Raca'),
        ),
    ]
