# Generated by Django 3.0.3 on 2020-02-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_cadastro', '0016_candidato_raca'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelEnsino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.IntegerField()),
                ('titulo', models.CharField(max_length=50)),
            ],
        ),
    ]
