# Generated by Django 3.0.3 on 2020-02-27 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pre_cadastro', '0017_nivelensino'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='nivel_ensino',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pre_cadastro.NivelEnsino'),
        ),
    ]
