# Generated by Django 3.0.3 on 2020-02-27 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pre_cadastro', '0018_candidato_nivel_ensino'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoInstituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.IntegerField()),
                ('titulo', models.CharField(max_length=30)),
                ('apelido', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='candidato',
            name='tipo_instituicao',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pre_cadastro.TipoInstituicao'),
        ),
    ]
