version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080
  
  mailcatcher:
    image: schickling/mailcatcher
    restart: always
    ports:
      - 1080:1080

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/pre_inscricao
    ports:
      - 8000:8000
    depends_on:
      - db