#!/bin/sh
python manage.py loaddata nacionalidade.yaml
python manage.py loaddata nacionalidade.yaml
python manage.py loaddata estado.yaml
python manage.py loaddata estado_civil.yaml
python manage.py loaddata pais_origem.yaml
python manage.py loaddata raca.yaml
python manage.py loaddata responsavel.yaml
python manage.py loaddata sexo.yaml
python manage.py loaddata tipo_sanguineo.yaml
python manage.py loaddata transporte_publico.yaml
python manage.py loaddata zona_residencial.yaml
python manage.py loaddata nivel_ensino.yaml
python manage.py loaddata tipo_instituicao.yaml
python manage.py loaddata ano_conclusao.yaml
python manage.py loaddata tipo_transtorno.yaml
python manage.py loaddata tipo_transporte.yaml
python manage.py loaddata tipo_veiculo.yaml
python manage.py loaddata emissao_rg.yaml
python manage.py loaddata tipo_certidao.yaml
python manage.py loaddata periodo_letivo.yaml
python manage.py loaddata turno.yaml
python manage.py loaddata forma_ingresso.yaml
python manage.py loaddata polo.yaml
python manage.py loaddata convenio.yaml
python manage.py loaddata tipo_superdotacao.yaml
python manage.py loaddata tipo_necessidade_especial.yaml
