#!/bin/sh

python manage.py loaddata ./dominio_suap/fixtures/ano_conclusao.yaml
python manage.py loaddata ./dominio_suap/fixtures/ano_letivo.yaml
python manage.py loaddata ./dominio_suap/fixtures/convenio.yaml
python manage.py loaddata ./dominio_suap/fixtures/estado.yaml
python manage.py loaddata ./dominio_suap/fixtures/estado_civil.yaml
python manage.py loaddata ./dominio_suap/fixtures/cidade.yaml
python manage.py loaddata ./dominio_suap/fixtures/forma_ingresso.yaml
python manage.py loaddata ./dominio_suap/fixtures/nacionalidade.yaml
python manage.py loaddata ./dominio_suap/fixtures/nivel_ensino.yaml
python manage.py loaddata ./dominio_suap/fixtures/orgao_emissao_rg.yaml
python manage.py loaddata ./dominio_suap/fixtures/pais_origem.yaml
python manage.py loaddata ./dominio_suap/fixtures/periodo_letivo.yaml
python manage.py loaddata ./dominio_suap/fixtures/polo.yaml
python manage.py loaddata ./dominio_suap/fixtures/raca.yaml
python manage.py loaddata ./dominio_suap/fixtures/responsavel.yaml
python manage.py loaddata ./dominio_suap/fixtures/sexo.yaml
python manage.py loaddata ./dominio_suap/fixtures/tipo_certidao.yaml
python manage.py loaddata ./dominio_suap/fixtures/tipo_instituicao.yaml
python manage.py loaddata ./dominio_suap/fixtures/tipo_necessidade_especial.yaml
python manage.py loaddata ./dominio_suap/fixtures/tipo_sanguineo.yaml
python manage.py loaddata ./dominio_suap/fixtures/tipo_superdotacao.yaml
python manage.py loaddata ./dominio_suap/fixtures/tipo_transporte.yaml
python manage.py loaddata ./dominio_suap/fixtures/tipo_transtorno.yaml
python manage.py loaddata ./dominio_suap/fixtures/tipo_veiculo.yaml
python manage.py loaddata ./dominio_suap/fixtures/transporte_publico.yaml
python manage.py loaddata ./dominio_suap/fixtures/turno.yaml
python manage.py loaddata ./dominio_suap/fixtures/zona_residencial.yaml
python manage.py loaddata ./dominio_suap/fixtures/matriz_curso.yaml

python manage.py loaddata ./solicitacao/fixtures/documentacao.yaml
