from django.contrib import admin
# from import_export.admin import ImportExportModelAdmin
from .models import *

# @admin.register(Nacionalidade)
# @admin.register(Sexo)
# @admin.register(EstadoCivil)
# @admin.register(Responsavel)
# @admin.register(Estado)
# @admin.register(ZonaResidencial)
# @admin.register(TransportePublico)
# @admin.register(TipoSanguineo)
# @admin.register(PaisOrigem)
# @admin.register(Raca)
# @admin.register(NivelEnsino)
# @admin.register(TipoInstituicao)
# @admin.register(AnoConclusao)
# @admin.register(NecessidadeEspecial)
# @admin.register(TipoTranstorno)
# @admin.register(Superdotacao)
# @admin.register(TipoTransporte)
# @admin.register(TipoVeiculo)
# @admin.register(EmissaoRg)
# @admin.register(TipoCertidao)
# @admin.register(PeriodoLetivo)
# @admin.register(Turno)
# @admin.register(FormaIngresso)
# @admin.register(Polo)
# @admin.register(Convenio)
