# Generated by Django 3.0.3 on 2020-04-17 14:28

from django.db import migrations, models
import django.db.models.deletion
import solicitacao.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnoConclusao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True)),
                ('titulo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Ano de conclusão',
                'verbose_name_plural': 'Anos de conclusão',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='AnoLetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True)),
                ('titulo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Ano letivo',
                'verbose_name_plural': 'Anos letivos',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True)),
                ('titulo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Convênio',
                'verbose_name_plural': 'Convênios',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='CotaMEC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True)),
                ('titulo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Cota MEC',
                'verbose_name_plural': 'Cotas MEC',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='CotaSISTEC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True)),
                ('titulo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Cota SISTEC',
                'verbose_name_plural': 'Cotas SISTEC',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True)),
                ('titulo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True)),
                ('titulo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Estado civil',
                'verbose_name_plural': 'Estados civis',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='FormaIngresso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True)),
                ('titulo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Forma de ingresso',
                'verbose_name_plural': 'Formas de ingressos',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='LinhaPesquisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True)),
                ('titulo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Linha de pesquisa',
                'verbose_name_plural': 'Linhas de pesquisas',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='MatrizCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True)),
                ('titulo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Matriz/Curso',
                'verbose_name_plural': 'Matrizes/Cursos',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Nacionalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True)),
                ('titulo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Nacionalidade',
                'verbose_name_plural': 'Nacionalidades',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='NivelEnsino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True)),
                ('titulo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Nível de ensino',
                'verbose_name_plural': 'Níveis de ensino',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='OrgaoEmissorRG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True)),
                ('titulo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Órgão emissor de RG',
                'verbose_name_plural': 'Órgãos emissores de RG',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='PaisOrigem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True)),
                ('titulo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'País de origem',
                'verbose_name_plural': 'Países de origem',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoLetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True)),
                ('titulo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Período letivo',
                'verbose_name_plural': 'Períodos letivos',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Polo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True)),
                ('titulo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Pólo',
                'verbose_name_plural': 'Pólos',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True)),
                ('titulo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Raça',
                'verbose_name_plural': 'Raças',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True)),
                ('titulo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True)),
                ('titulo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Sexo',
                'verbose_name_plural': 'Sexos',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='TipoCertidao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True)),
                ('titulo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo de certidão',
                'verbose_name_plural': 'Tipos de certidões',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='TipoInstituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True)),
                ('titulo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo de instituição',
                'verbose_name_plural': 'Tipos de instituições',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='TipoNecessidadeEspecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True)),
                ('titulo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Necessidade especial',
                'verbose_name_plural': 'Necessidades especiais',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='TipoSanguineo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True)),
                ('titulo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo sanguíneo',
                'verbose_name_plural': 'Tipos sanguíneos',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='TipoSuperdotacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True)),
                ('titulo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Supordotação',
                'verbose_name_plural': 'Supordotações',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='TipoTransporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True)),
                ('titulo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo de transporte',
                'verbose_name_plural': 'Tipos de transporte',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='TipoTranstorno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True)),
                ('titulo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo de transtorno',
                'verbose_name_plural': 'Tipos de transtornos',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='TipoVeiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True)),
                ('titulo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo de veículo',
                'verbose_name_plural': 'Tipos de veículos',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='TransportePublico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True)),
                ('titulo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Transporte público',
                'verbose_name_plural': 'Transportes públicos',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True)),
                ('titulo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='ZonaResidencial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True)),
                ('titulo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Zona residêncial',
                'verbose_name_plural': 'Zonas residênciais',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('estado', solicitacao.fields.FK(on_delete=django.db.models.deletion.CASCADE, to='dominio_suap.Estado', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['titulo'],
            },
        ),
    ]
