# Generated by Django 3.0.3 on 2020-02-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canditado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=350)),
                ('email', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14)),
            ],
        ),
    ]
