# Generated by Django 3.0.3 on 2020-02-05 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Canditado',
            new_name='Candidado',
        ),
    ]
