# Generated by Django 3.0.3 on 2020-02-11 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20200205_1734'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Candidado',
            new_name='Candidato',
        ),
    ]
