# Generated by Django 3.0.3 on 2020-04-05 21:36

from django.db import migrations, models
import django.db.models.deletion
import solicitacao.fields


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selecionado',
            options={'verbose_name': 'Selecionado', 'verbose_name_plural': 'Selecionados'},
        ),
        migrations.AlterField(
            model_name='selecionado',
            name='chamada',
            field=solicitacao.fields.FK(on_delete=django.db.models.deletion.CASCADE, to='solicitacao.Chamada', verbose_name='Chamada'),
        ),
        migrations.CreateModel(
            name='PublicAuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, verbose_name='Token')),
                ('criado_em', models.DateTimeField(auto_now=True, verbose_name='Criado em')),
                ('chamada', solicitacao.fields.FK(on_delete=django.db.models.deletion.CASCADE, to='solicitacao.Chamada', verbose_name='Chamada')),
                ('selecionado', solicitacao.fields.FK(on_delete=django.db.models.deletion.CASCADE, to='solicitacao.Selecionado', verbose_name='Selecionado')),
            ],
        ),
    ]
