# Generated by Django 3.0.3 on 2020-03-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chamada',
            options={'verbose_name': 'Chamada', 'verbose_name_plural': 'Chamadas'},
        ),
        migrations.AlterModelOptions(
            name='edital',
            options={'verbose_name': 'Edital', 'verbose_name_plural': 'Editais'},
        ),
        migrations.RemoveField(
            model_name='chamada',
            name='tipo_convocacao',
        ),
        migrations.AddField(
            model_name='chamada',
            name='tipo_chamada',
            field=models.CharField(choices=[('I', 'Inicial'), ('R', 'Remanescente')], default='I', max_length=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='chamada',
            name='chamada',
            field=models.CharField(max_length=255, verbose_name='Chamada'),
        ),
    ]
