# Generated by Django 3.0.3 on 2020-04-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicauthtoken',
            name='chamada',
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='complemento',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Complemento'),
        ),
    ]
