# Generated by Django 3.0.3 on 2020-04-12 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoConcluida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veracidade', models.BooleanField(verbose_name='Confirmo que todas as informacões declaradas são verdadeiras.')),
                ('confirmacao', models.BooleanField(verbose_name='Confirmo que após concluir o meu cadastro não poderei mais alterar os dados e arquivos enviados.')),
                ('sha512_solicitacao', models.CharField(max_length=255, verbose_name='SHA 512 da solicitação')),
                ('solicitacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='solicitacao.Solicitacao', verbose_name='Solicitação')),
            ],
        ),
    ]
