# Generated by Django 3.0.3 on 2020-04-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0002_auto_20200419_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamada',
            name='instrucoes_adicionais',
            field=models.TextField(blank=True, null=True, verbose_name='Instruções adicionais'),
        ),
    ]
