# Generated by Django 3.0.3 on 2020-04-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0002_solicitacaoconcluida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacaoconcluida',
            options={'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AddField(
            model_name='solicitacaoconcluida',
            name='autodeclaracao_etnia',
            field=models.BooleanField(default=None, verbose_name='Autodeclaro minha Etnia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacaoconcluida',
            name='organizacao_didatica',
            field=models.BooleanField(default=None, verbose_name='Declaro que estou ciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacaoconcluida',
            name='penal',
            field=models.BooleanField(default=None, verbose_name='Declaro que estou ciente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitacaoconcluida',
            name='veracidade',
            field=models.BooleanField(verbose_name='Reconheço que as informações prestadas são verdadeiras.'),
        ),
    ]
