# Generated by Django 3.0.3 on 2020-03-30 20:50

from django.db import migrations, models
import django.db.models.deletion
import solicitacao.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dominio_suap', '0001_initial'),
        ('solicitacao', '0002_auto_20200330_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='ano_letivo',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='forma_ingresso',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='matriz_curso',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='periodo_letivo',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='polo',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='turno',
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='email_pessoal',
            field=models.EmailField(blank=True, help_text='É por este email que você configurará sua senha e acompanhará suas aulas. Informe um que costume acessar.', max_length=254, null=True, verbose_name='E-mail pessoal'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='email_responsavel',
            field=models.EmailField(blank=True, max_length=250, null=True, verbose_name='Email do responsável'),
        ),
        migrations.CreateModel(
            name='Selecionado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF')),
                ('passaporte', models.CharField(blank=True, max_length=250, null=True, verbose_name='Passaporte')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('nome_social', models.CharField(blank=True, help_text='Só preencher este campo a pedido do aluno e de acordo com a legislação vigente.', max_length=250, null=True, verbose_name='Nome social')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('ano_letivo', solicitacao.fields.FK(on_delete=django.db.models.deletion.CASCADE, to='dominio_suap.AnoLetivo', verbose_name='Ano letivo')),
                ('forma_ingresso', solicitacao.fields.FK(on_delete=django.db.models.deletion.CASCADE, to='dominio_suap.FormaIngresso', verbose_name='Forma de ingresso')),
                ('matriz_curso', solicitacao.fields.FK(on_delete=django.db.models.deletion.CASCADE, to='dominio_suap.MatrizCurso', verbose_name='Matriz/Curso')),
                ('nacionalidade', solicitacao.fields.FK(on_delete=django.db.models.deletion.CASCADE, to='dominio_suap.Nacionalidade', verbose_name='Nacionalidade')),
                ('periodo_letivo', solicitacao.fields.FK(on_delete=django.db.models.deletion.CASCADE, to='dominio_suap.PeriodoLetivo', verbose_name='Período letivo')),
                ('polo', solicitacao.fields.NullFK(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dominio_suap.Polo', verbose_name='Polo EAD')),
                ('turno', solicitacao.fields.FK(on_delete=django.db.models.deletion.CASCADE, to='dominio_suap.Turno', verbose_name='Turno')),
            ],
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='selecionado',
            field=solicitacao.fields.FK(default=None, on_delete=django.db.models.deletion.CASCADE, to='solicitacao.Selecionado', verbose_name='Selecionado'),
            preserve_default=False,
        ),
    ]
