# Generated by Django 3.0.3 on 2020-03-30 20:58

from django.db import migrations
import django.db.models.deletion
import solicitacao.fields


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0003_auto_20200330_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='selecionado',
            name='chamada',
            field=solicitacao.fields.FK(default=None, on_delete=django.db.models.deletion.CASCADE, to='solicitacao.Chamada', verbose_name='Edital'),
            preserve_default=False,
        ),
    ]
