# Generated by Django 3.0.3 on 2020-04-19 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0003_chamada_instrucoes_adicionais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edital',
            name='tem_pce',
        ),
        migrations.RemoveField(
            model_name='edital',
            name='tem_ppi',
        ),
    ]
