# Generated by Django 3.0.3 on 2020-04-21 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0004_auto_20200419_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['documentacao'], 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='data_conclusao_intercambio',
            field=models.DateField(blank=True, help_text="No formato 'dd/mm/aaaa'.", null=True, verbose_name='Conclusão do intercâmbio'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='data_emissao_certidao',
            field=models.DateField(blank=True, help_text="No formato 'dd/mm/aaaa'.", null=True, verbose_name='Data de emissão da certidão civil'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='data_emissao_rg',
            field=models.DateField(blank=True, help_text="No formato 'dd/mm/aaaa'.", null=True, verbose_name='Data de emissão do RG'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='data_emissao_titulo_eleitor',
            field=models.DateField(blank=True, help_text="No formato 'dd/mm/aaaa'.", null=True, verbose_name='Data de emissão do título de eleitor'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='data_nascimento',
            field=models.DateField(help_text="No formato 'dd/mm/aaaa'.", verbose_name='Data de nascimento'),
        ),
    ]
