# Generated by Django 3.0.3 on 2020-05-13 01:10

from django.db import migrations, models
import django.db.models.deletion
import solicitacao.fields


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0005_auto_20200421_0150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='')),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('solicitacao', solicitacao.fields.FK(on_delete=django.db.models.deletion.CASCADE, to='solicitacao.Solicitacao', verbose_name='Solicitação')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
            },
        ),
    ]
